### ISSUE TITLE
test rapido non verificato

### ISSUE THREAD

**Issue by st4nny** [berdav/greenpass#10]
Ciao,
ho provato a verificare un qr di un test rapido in corso di validità,
i dati vengono letti correttamente ma la verifica non passa correttamente fino alla fine.
Come output ho:
Certificate type               Test
Release Country                IT
Release Date                   2021-09-29 12:32:23+00:00
Expiration Date                2023-05-12 00:00:00+00:00
Version                        1.0.0
Date of Birth                   -------
First Name                     -------
Family Name                   -------
  Target disease               Covid19
  Vaccination or test Country  IT
  Certificate Issuer           Ministero della Salute
  Certificate ID              -------
  Manufacturer and type        VivaDiag Pro SARS-CoV-2 Ag Rapid Test
  Test type                    rapid
  Test result                  Negative
  Testing center               -------
  Test Date                    0 (Expired since 0 hours, 0 days)
Verified                       True

la mia data di sistema è ok, la mia macchina linux ad ora mi risponde: gio 30 set 2021, 01.08.27, CEST
Con verificac19 o altri validatori il qr passa correttamente, sapresti dirmi dov'è il problema?
Il gp del vaccino passa correttamente.

**Comment by berdav** [comment]
Ciao,

e' strambo, probabilmente il filtro della data non passa correttamente, riesci a verificare che la data del tuo gp abbia un formato simile a questo?

2021-07-20T09:16:00+02:00

Ho aggiunto un nuovo switch `--raw` che puoi usare per tirare fuori le informazioni dal gp in formato JSON, puoi provare con un comando come questo con l'ultima versione scaricata dal master:

```bash
./greenpass --raw --pdf /vagrant/dgc-rob.pdf  | jq '.["-260"]["1"]["t"][].sc'
```

Se la data non ha il formato riportato sopra, riesci a dirmi in che formato e' salvata?

**Comment by st4nny** [comment]
Ciao,
ecco qui la mia risposta:
"2021-09-29T14:32:00+02:00"

quindi direi che ci siamo.

**Comment by st4nny** [comment]
Non conosco python, ho fatto un minimo di debug e stampando queste a schermo:

print(cert_info[0])
print(dn)
print(sd)
print(testcollectiondate)
print(testtype)
print(vaccinedate)
print(vaccine)

ottengo:
Total doses
0
0
0
LP217198-3
None
None

quindi mi sembra di capire che quando si va a calcolare hours_to_valid, remaining_hours da testcollectiondate si ottenga sempre zero.

**Comment by st4nny** [comment]
Non conosco python, ho fatto un minimo di debug e sembra
che lo script fallisca a riga 652 sul parsing della data.
Ho commentato il try e ottengo in risposta:
ValueError: time data '2021-09-29T14:32:00+02:00' does not match format '%Y-%m-%dT%H:%M:%S%z'

Cercando un pò ho trovato questo:
https://stackoverflow.com/questions/50489198/strptime-unable-to-resolve-timezone-value-0200
sembra che datetime.strptime non gestisca i due punti della timezone

**Comment by berdav** [comment]
Ciao,

sembra che tu abbia una versione molto vecchia di Python 3, con le versioni nuove il problema non si pone

Ho provato questo script sulle versioni che trovi dopo il codice:

```python3
import datetime
x = '2021-09-29T14:32:00+02:00'
res1= datetime.datetime.strptime(x, '%Y-%m-%dT%H:%M:%S%z')

print(res1)
```

- Python 3.9.7, funziona
- Python 3.10.0rc2, funziona
- Python 3.9.5, funziona
- Python 3.6.9, non funziona

Sembra riportare con quanto indicato dalla documentazione di datetime:
```
Changed in version 3.7: When the %z directive is provided to the strptime() method, the UTC offsets can have a colon as a separator between hours, minutes and seconds. For example, '+01:00:00' will be parsed as an offset of one hour. In addition, providing 'Z' is identical to '+00:00'.
```

Rimuoverei il : *dopo al + nella stringa* (se non c'e' il : in qualche gp si potrebbe rompere tutto)

Una cosa come:
```python3
import sys
import datetime
x = '2021-09-29T14:32:00+02:00'

s = x.split("+")
x = "+".join((s[0], s[1].replace(":","")))

res1= datetime.datetime.strptime(x, '%Y-%m-%dT%H:%M:%S%z')
print(res1)
```

Non so se aggiungere un controllo di versione o solo un commento.

Faccio un commit a brevissimo,  ciao,
D.

**Comment by berdav** [comment]
Ovviamente il controllo e' un po' piu' complesso perche' richiede anche di controllare timezone "in anticipo" rispetto a +00:00, ad esempio -02:00.

**Comment by st4nny** [comment]
Confermo, di default sulla macchina ho una 3.6.9
Sono su redhat.. è molto conservativa in effetti :D Ho installato python3.9, precisamente la 3.9.2
e ora lo calcola correttamente, oramai scaduto da un'ora.
Direi che basta così, valuta tu se merita fixare per versioni vecchiotte.

Un saluto e grazie per la disponibilità

**Comment by berdav** [comment]
Python 3.6 e' stato rilasciato nel 2016, ci metto una nota sopra, poi lo togliero' tra qualche tempo (ma spero non servira' piu' lo script se non per ragioni storiche ;) ).

Grazie per il debug e l'interesse!

Fixed in https://github.com/berdav/greenpass/tree/issue-10-test-rapido-non-verificato

Ciao,
D.
