### ISSUE TITLE
dgc recovery Expired ma ancora valida per VerificaC19

### ISSUE THREAD

**Issue by st4nny** [berdav/greenpass#33]
Ciao,
non ricordo se nel tempo la data di validità di una dgc di tipo recovery è cambiata.
Comunque stante ai settings sono +180gg dal giorno della validità della certificazione.
Mi sono ritrovato con un pdf di una recovery valida dai primi di giugno, sulla carta c'era scritto valida fino ai primi di novembre
ma l'app VerificaC19 la da buona ed in teoria ci starebbe perchè fino a dicembre (+180) sarebbe valida,
vedo che viene valutata la data di scadenza presa direttamente dal certificato quindi non viene applicata la rules dai settings quindi ci sta che ritornasse Scaduto.

Che dici?

**Comment by berdav** [comment]
Ciao,

mi era abbastanza oscuro se l'app controllasse la data sul certificato o sulle settings (non capisco perche' debbano esserci due informazioni ridondandi), direi che la cosa migliore e' mettere uno switch che di default abilita il controllo della data di scadenza dalle settings, non dal certficato e aggiornare la test suite.

In settimana cerco di fare un fix.

Ciao,
D.

**Comment by berdav** [comment]
Ciao, come sempre grazie!

ho aggiunto uno switch (`--recovery-expiration`).  In grado di riabilitare il controllo prendendo come data il minimo tra la data di scadenza scritta nel certificato e la data delle settings.

Di default considera solo le settings.

Trovi tutto nel branch issue-33-verification-recovery, gia' mergiato sul master.
