### ISSUE TITLE
Scadenza Dose + Guarigione + Richiamo errata?

### ISSUE THREAD

**Issue by Nightmare** [berdav/greenpass#39]
Non sono sicuro del calcolo che viene effettuato sulla scadenza della vaccinazione, ma

ho verificato un GP di una persona che ha effettuato 1 Dose, Guarigione, Richiamo, risulta 2/1 Moderna quindi Booster
ma Data Vaccino (2021-11-29) risulta scaduta da 11 giorni 

non dovrebbe essere 6/9 mesi?

**Comment by berdav** [comment]
Ciao,

per ora ho visto solo booster con numero di dosi effettuate / numero di dosi totali con il numero di dosi effettuate uguale a quelle totali (3/3 2/2 etc).

Aggiorno il controllo e ti faccio sapere.

**Comment by berdav** [comment]
Ok, ho creato un fix nel branch [issue-39-booster-validity](https://github.com/berdav/greenpass/tree/issue-39-booster-validity)

Riesci a controllare con quel greenpass?

**Comment by Nightmare** [comment]
Perfetto, ecco il risultato.

Doses 2/1
Vaccine Date 2021-11-29 00:00:00+00:00 (5191 Hours left, 216 Days, ~ 7 Months)

**Comment by berdav** [comment]
Mi sembra che ora riporti (ancora 7 mesi, visto che ne sono passati circa due)

Ho riportato tutto nel master e fatto una nuova versione, grazie mille!!! :)
