### ISSUE TITLE
Input da scanner

### ISSUE THREAD

**Issue by AntoBaldo** [berdav/greenpass#4]
Ciao,
Se come input vorrei usare uno scanner qr invece di un file?

Hi,
If as input I would like to use a qr scanner instead of a file?

**Comment by berdav** [comment]
Ciao, se lo scanner QR ritorna in output in stdout una stringa con il contenuto del QR code puoi usare una pipe come nel caso di zbarimg:

Hi, if you're using a QR scanner that returns a plaintext with the content of the QR code over the stdout you can use a pipe, like the case of zbarimg:

```
zbarcam --raw -q1 | greenpass --txt -
```

**Comment by berdav** [comment]
Ho aggiunto una nota nel README del commit 089c52c4f88237ed4fddc9dce77eff525636e692 .

Chiudo questa issue, se non dovesse funzionare qualcosa la riapriro'.
